### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by emersonbottero** [davidwittenbrink/facebook-login#8]
even the Demo don't show the login button

**Comment by emersonbottero** [comment]
update information..
console response
The resource at "http://graph.facebook.com//picture" was blocked because tracking protection is enabled.[Learn More]

don't know what to do.

**Comment by davidwittenbrink** [comment]
Ok thanks for pointing this out. Will take a look as soon as possible.

**Comment by davidwittenbrink** [comment]
Could you tell me what exactly you were doing when the error occurred? Was not able to reproduce it so far.

**Comment by emersonbottero** [comment]
I am using it in the polymer starter Kit project
I just used you element and is does not shoe the button

You can try addin it in a new polymer starter kit project or you can see it in here

http://kopempack.com.br/fbtest

Click in user and you should see the button. (I know it will not connect until i configure the site url. it is just an example so you can see for yourself.

thanks

**Comment by davidwittenbrink** [comment]
I think the problem is that you've imported the EcmaScript 2015 version of the button. I have developed the button using new language features that are not compatible with every browser and then used a tool called [Babel](https://babeljs.io/) to transpile it into code that runs on every browser.

Long story short:
Instead of importing the element using
`<link rel="import" href="../bower_components/facebook-login/facebook-login.html">
`
in your elements.html, use
`<link rel="import" href="../bower_components/facebook-login/dist/facebook-login.html">
`.
If you still run into problems just let me know :)

**Comment by emersonbottero** [comment]
You nail it. I already change the example. Thanks.

Em qui, 17 de dez de 2015 09:03, David Wittenbrink <notifications@github.com>
escreveu:

**Comment by davidwittenbrink** [comment]
:thumbsup:
